config/routes.rb
Rails.application.routes.draw do

  root 'requests#analyze'
  get '/analyze', :to => 'requests#analyze', as: 'analyze'
  post '/analyze', :to => 'requests#analyzed', as: 'analyzed'

  get '/about', :to => 'requests#about', as: 'about'

  post '/search', :to => 'requests#search', as: 'search'

  get '/trends', :to => 'requests#trends', as: 'trends'

  get '/show', :to => 'requests#show'


end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
require "./config/initializers/twitter"
require "httparty"
require 'twitter'
require 'excon'
require 'json'
require 'magic_cloud'
require 'rmagick'
require 'area'


class RequestsController < ApplicationController
  # def about
  #   @disclaimer[:notice] = "**Tweet analysis is currently limited to tweets composed in English."
  # end

  def self.call_twitter(handle)
    # Replace underscores in Twitter handles in preparation for URL encoding
    handle.gsub!("_", "%5F")

    # Exchange our oauth_token and oauth_token secret for the AccessToken instance.
    access_token = prepare_access_token

    # use the access token as an agent to get the user's tweets
    logger.info("Making request")
    response = access_token.request(:get, "https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=" + handle + "&count=100")
    logger.info("response is: #{response.body}")
    tweets = JSON.parse(response.body)

    @results_hash = {}

    @results_hash["username"] = tweets[0]["user"]["screen_name"]

    #Convert user's free form location to state abbreviation.
    if (tweets[0]["user"]["location"].to_zip != nil || tweets[0]["user"]["location"].to_zip == [])
      @user_location = tweets[0]["user"]["location"].to_zip
      if (@user_location.length > 0)
        @user_location = @user_location[0].to_region

        @results_hash["location"] = @user_location[-2, 2]
      end
    end

    puts @results_hash

    # Compile all tweet text into a single string for analysis
    @user_text = ""
    tweets.each do |tweet|
      @user_text = @user_text + " " + tweet["text"]
    end

    # Remove Twitter handles and hashtags from text to be analyzed
    @word_array = @user_text.split(" ")
    @word_array.each do |word|
      if word[0] == "@" || word[0] == "#"
        @word_array.delete(word)
      end
    end
    @user_text = @word_array.join(" ")

    @user_text = @user_text[0...2000]

    RequestsController.call_watson(@user_text)

  end

  def self.call_watson(tweets)
    response = Excon.post("https://gateway.watsonplatform.net/tone-analyzer/api/" + "/v3/tone?version=2016-05-19",
    :headers => {
    "Content-Type" => "text/plain"
    },
    :body => @user_text,
    :password => "iZTY7ZvkKYix",
    :user => "f350af80-6ec2-4b48-8940-9c62b84819cf")

    response = JSON.parse(response.body)

    RequestsController.compile(response)
  end

  def self.compile(response)
    @characteristics_hash = {}

    response["document_tone"]["tone_categories"].each do |result_types|
      result_types["tones"].each do |trait|
        @characteristics_hash[trait["tone_name"]] = trait["score"]
      end
    end



    @results_hash["traits"] = @characteristics_hash

    # Save new query results to database
    if (Request.find_by(:username => "#{@results_hash["username"]}") == nil)
      Request.create(username: @results_hash["username"],
      location: @results_hash["location"],
      anger: @results_hash["traits"]["Anger"],
      disgust: @results_hash["traits"]["Disgust"],
      fear: @results_hash["traits"]["Fear"],
      joy: @results_hash["traits"]["Joy"],
      sadness: @results_hash["traits"]["Sadness"],
      analytical: @results_hash["traits"]["Analytical"],
      confident: @results_hash["traits"]["Confident"],
      tentative: @results_hash["traits"]["Tentative"],
      openness: @results_hash["traits"]["Openness"],
      conscientiousness: @results_hash["traits"]["Conscientiousness"],
      extraversion: @results_hash["traits"]["Extraversion"],
      agreeableness: @results_hash["traits"]["Agreeableness"],
      emotional_range: @results_hash["traits"]["Emotional Range"]
      )
    end

    return @characteristics_hash

  end

  def trends
    @states = Request.select(:location).map(&:location).uniq
  end

  def show
    # DRY out this method. So ugly.
    @selected_state = params[:state_results][:location]
    @average_anger = 0
    @average_disgust = 0
    @average_fear = 0
    @average_joy = 0
    @average_sadness = 0
    @average_analytical = 0
    @average_confident = 0
    @average_tentative = 0
    @average_openness = 0
    @average_conscientiousness = 0
    @average_extraversion = 0
    @average_agreeableness = 0
    @average_emotional_range = 0

    @state_results = Request.where(["location = :u", { u: params[:state_results][:location] }])

    @state_results.each do |record|
      @average_anger += record.anger
      @average_disgust += record.disgust
      @average_fear += record.fear
      @average_joy += record.joy
      @average_sadness += record.sadness
      @average_analytical += record.analytical
      @average_confident += record.confident
      @average_tentative += record.tentative
      @average_openness += record.openness
      @average_conscientiousness += record.conscientiousness
      @average_extraversion += record.extraversion
      @average_agreeableness += record.agreeableness
      @average_emotional_range += record.emotional_range
    end
    @average_anger = ((@average_anger / @state_results.length)*100).round
    @average_disgust = ((@average_disgust / @state_results.length)*100).round
    @average_fear = ((@average_fear / @state_results.length)*100).round
    @average_joy = ((@average_joy / @state_results.length)*100).round
    @average_sadness = ((@average_sadness / @state_results.length)*100).round
    @average_analytical = ((@average_analytical / @state_results.length)*100).round
    @average_confident = ((@average_confident / @state_results.length)*100).round
    @average_tentative = ((@average_tentative / @state_results.length)*100).round
    @average_openness = ((@average_openness / @state_results.length)*100).round
    @average_conscientiousness = ((@average_conscientiousness / @state_results.length)*100).round
    @average_extraversion = ((@average_extraversion / @state_results.length)*100).round
    @average_agreeableness = ((@average_agreeableness / @state_results.length)*100).round
    @average_emotional_range = ((@average_emotional_range / @state_results.length)*100).round
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Fathom</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>

  <body>
    <style>
      .bg-1 {
          background-color: #1abc9c; /* Green */
          color: #ffffff;
      }
      .bg-2 {
          background-color: #474e5d; /* Dark Blue */
          color: #ffffff;
      }
      .bg-3 {
          background-color: #ffffff; /* White */
          color: #555555;
      }

      .container-fluid {
          padding-top: 50px;
          padding-bottom: 50px;
      }

      .navbar {
          padding-top: 15px;
          padding-bottom: 15px;
          border: 0;
          border-radius: 0;
          margin-bottom: 0;
          font-size: 12px;
          letter-spacing: 5px;
      }

      .navbar-nav li a:hover {
          color: #1abc9c !important;
      }

      .bg-4 {
          background-color: #2f2f2f;
          color: #ffffff;
      }

      body {
          font: 20px "Montserrat", sans-serif;
          line-height: 1.8;
          color: #f5f6f7;
      }

      .input {
        color: black;
        display: inline;
      }

      table, th, td {
        text-align: center;
        margin-left: auto;
        margin-right: auto;
        border-style: solid;
        border-color: white;
      }

      p {font-size: 16px;}

      .btn {
        font-size: 18px;
        color: #1abc9c;
        filter: brightness(5%);
      }

      .btn:hover {
        filter: invert(100%);
      }

      .handle {
        font-size: 26px;
        display: inline;
      }

      .table {
        width: 650px;
      }

      th {
        font-size: 32px;
      }

      .cloud {
        border-radius: 30px;
      }
    </style>


    <div class="container-fluid bg-1 text-center">
      <div class="yield"><%= yield %></div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>

      <footer class="container-fluid bg-4 text-center">
        <p></p>
      </footer>
    </div>


  </body>
</html>

app/views/requests/about.html.erb
<br>
<div class="container-fluid bg-1 text-center">
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div style="font-size:42px;font-weight:400;line-height:46.2px;color:white;"><a style="font-size:42px;font-weight:400;line-height:46.2px;color:white;" class="navbar-brand" href="#"><%= link_to "fathom", root_path %></a></div>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "TRENDS", trends_path %></li>
          <li class="active"><%= link_to "ABOUT", about_path %></li>
        </ul>
      </div>
    </div>
  </nav>
<br>
<h3><%= t('about_title') %></h3>
<br>
<p><%= t('about_p1') %></p>
<p><%= t('about_p2') %><a href="https://github.com/abrown152/fathom" target="_blank">here</a>.</p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</div>

app/views/requests/analyze.html.erb
<div class="container-fluid bg-1 text-center">
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div style="font-size:42px;font-weight:400;line-height:46.2px;color:white;"><a style="font-size:42px;font-weight:400;line-height:46.2px;color:white;" class="navbar-brand" href="#"><%= link_to "fathom", root_path %></a></div>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "TRENDS", trends_path %></li>
          <li><%= link_to "ABOUT", about_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <br>
  <div class="form-group">
    <h3><%= t('analyze_title') %></h3>
    <%= form_tag analyze_path do %>
      <div class="handle"><%= label_tag(:q, "@") %></div>
      <div class="input"><%= text_field_tag(:q) %></div>
      <button type="submit" class="btn btn-default">Analyze!</button>
    <% end %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>

</div>

app/views/requests/analyzed.html.erb
<div class="container-fluid bg-1 text-center">
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div style="font-size:42px;font-weight:400;line-height:46.2px;color:white;"><a style="font-size:42px;font-weight:400;line-height:46.2px;color:white;" class="navbar-brand" href="#"><%= link_to "fathom", root_path %></a></div>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "TRENDS", trends_path %></li>
          <li><%= link_to "ABOUT", about_path %></li>
        </ul>
      </div>
    </div>
  </nav>

<h3><%= t('analyzed_title') %><%= params[:q] %></h3>
<h3><%= t('analyzed_results') %></h3><br>
  <%results = RequestsController.call_twitter(params[:q]) %>
  <table class="table">
    <tr>
      <th class="headers"><%= t('analyzed_trait') %></th>
      <th class="headers"><%= t('analyzed_score') %></th>
    </tr>

    <div><% word_array = [
      ["anger", 13],
      ["disgust", 10],
      ["fear", 34],
      ["joy", 10],
      ["sad", 5],
      ["analytical", 1],
      ["confident", 16],
      ["tentative", 7],
      ["open", 4],
      ["conscientious", 2],
      ["extravert", 18],
      ["agreeable", 5],
      ["emotionally intelligent", 5]
      ] %></div>
    <div><% cloud = MagicCloud::Cloud.new(word_array, rotate: :free, scale: :log) %></div>
    <div><% rcloud = cloud.draw(600, 500) %></div>
    <div><% cloud_png = rcloud.to_blob {self.format="png"} %></div>
    <img class="cloud" src="data:image/png;base64,<%=
    Base64.encode64(cloud_png) %>">

    <br>
    <br>
    <% results.each do |trait_array| %>
    <tr>
      <td><%= trait_array[0] %></td>
      <td><%= (trait_array[1]*100).round %></td>
    </tr>
    <% end %>
  </table>
  <p><%= t('score_scale') %></p>
</div>

app/views/requests/index.html.erb
<h4>Please enter the text you'd like to analyze...</h4>
<%= form_tag analyze_path do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/requests/search.html.erb
<h1>Results</h1>

<% @search_results.each do |pair| %>
  <p><%= pair %></p>
<% end %>

app/views/requests/show.html.erb
<div class="container-fluid bg-1 text-center">
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div style="font-size:42px;font-weight:400;line-height:46.2px;color:white;"><a style="font-size:42px;font-weight:400;line-height:46.2px;color:white;" class="navbar-brand" href="#"><%= link_to "fathom", root_path %></a></div>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><%= link_to "TRENDS", trends_path %></li>
          <li><%= link_to "ABOUT", about_path %></li>
        </ul>
      </div>
    </div>
  </nav>
<br>
<h3><%= t('trend_title') %><%= @selected_state %></h3>
<br>

<table class="table">
  <tr>
    <th><%= t('analyzed_trait') %></th>
    <th><%= t('analyzed_score') %></th>
  </tr>
  <tr>
    <td><%= t('anger') %></td>
    <td><%= @average_anger %></td>
  </tr>
  <tr>
    <td><%= t('disgust') %></td>
    <td><%= @average_disgust %></td>
  </tr>
  <tr>
    <td><%= t('fear') %></td>
    <td><%= @average_fear %></td>
  </tr>
  <tr>
    <td><%= t('joy') %></td>
    <td><%= @average_joy %></td>
  </tr>
  <tr>
    <td><%= t('sadness') %></td>
    <td><%= @average_sadness %></td>
  </tr>
  <tr>
    <td><%= t('analytical') %></td>
    <td><%= @average_analytical %></td>
  </tr>
  <tr>
    <td><%= t('confident') %></td>
    <td><%= @average_confident %></td>
  </tr>
  <tr>
    <td><%= t('tentative') %></td>
    <td><%= @average_tentative %></td>
  </tr>
  <tr>
    <td><%= t('openness') %></td>
    <td><%= @average_openness %></td>
  </tr>
  <tr>
    <td><%= t('conscientiousness') %></td>
    <td><%= @average_conscientiousness %></td>
  </tr>
  <tr>
    <td><%= t('extraversion') %></td>
    <td><%= @average_extraversion %></td>
  </tr>
  <tr>
    <td><%= t('agreeableness') %></td>
    <td><%= @average_agreeableness %></td>
  </tr>
  <tr>
    <td><%= t('emotional_range') %></td>
    <td><%= @average_emotional_range %></td>
  </tr>
</table>
<p><%= t('score_scale') %></p>
<br>
<br>
<br>
<br>
<br>
<br>
</div>

app/views/requests/trends.html.erb
<div class="container-fluid bg-1 text-center">
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div style="font-size:42px;font-weight:400;line-height:46.2px;color:white;"><a style="font-size:42px;font-weight:400;line-height:46.2px;color:white;" class="navbar-brand" href="#"><%= link_to "fathom", root_path %></a></div>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
          <li class="active"><%= link_to "TRENDS", trends_path %></li>
          <li><%= link_to "ABOUT", about_path %></li>
        </ul>
      </div>
    </div>
  </nav>
<br>
<br>
<%= bootstrap_form_for :state_results, url: {action: "show"}, html: {method: "get"} do |f| %>
  <%= f.select :location, options_for_select(@states), {}, { id: 'state_select' } %>
  <%= f.submit "Go!" %>
<% end %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</div>